### ISSUE TITLE
Discord Async Event doesn't update rich presence when using variables inside np_setpresence();

### ISSUE THREAD

**Issue by GamerXLPro** [nkrapivin/NekoPresence#4]
Tried methods like calling np_update(); once every 5 seconds (as opposed by new discord "update presence" method, as you can update only 5 times every 20 seconds), deleting and creating the main NekoPresence object, manually forcing async updates and so on. Presence never updated after first initialization. Tried testing with variables or built-in variables (like mouse_x and mouse_y), only updated once and never again, even if np_update(); is being called.

No errors shown, everyting is working fine. Fresh project without any other objects inside, only NekoPresence

**Comment by nkrapivin** [comment]
> Tried methods like calling np_update(); once every 5 seconds (as opposed by new discord "update presence" method, as you can update only 5 times every 20 seconds), deleting and creating the main NekoPresence object, manually forcing async updates and so on. Presence never updated after first initialization. Tried testing with variables or built-in variables (like mouse_x and mouse_y), only updated once and never again, even if np_update(); is being called.
> 
> No errors shown, everyting is working fine. Fresh project without any other objects inside, only NekoPresence


np_update is meant to be called every Step.
